LOCAL_PATH := $(call my-dir)
ifeq ($(TARGET_DEVICE),st18c7bnn)
include $(call all-makefiles-under,$(LOCAL_PATH))
include $(CLEAR_VARS)

PROTECT_F_MOUNT_POINT  := $(TARGET_OUT_VENDOR)/protect_f
PROTECT_S_MOUNT_POINT := $(TARGET_OUT_VENDOR)/protect_s

$(PROTECT_F_MOUNT_POINT):
	@echo "Creating $(PROTECT_F_MOUNT_POINT)"
	@mkdir -p $(PROTECT_F_MOUNT_POINT)

$(PROTECT_S_MOUNT_POINT):
	@echo "Creating $(PROTECT_S_MOUNT_POINT)"
	@mkdir -p $(PROTECT_S_MOUNT_POINT)

ALL_DEFAULT_INSTALLED_MODULES += \
	$(PROTECT_F_MOUNT_POINT) $(PROTECT_S_MOUNT_POINT) \

KERNEL_OUT := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ

$(KERNEL_OUT):
	mkdir -p $(KERNEL_OUT)

INSTALLED_KERNEL_HEADERS: $(KERNEL_OUT)

endif
